# --- Configuración del Proyecto ---
site_name: "PGTEC"
site_url: https://pgtec-vrain.github.io/
site_description: Documentación técnica del proyecto PGTEC-VRAIN.
copyright: "© 2025 - 2026 PGTEC · VRAIN"
site_dir: public

# --- Repositorio ---
repo_url: https://github.com/pgtec-vrain/pgtec-vrain.github.io
repo_name: pgtec-vrain/pgtec-vrain.github.io
# --- Tema y Apariencia ---
theme:
  custom_dir: docs/overrides
  name: material
  logo: assets/images/logo_PGTEC.svg
  favicon: assets/images/logo_PGTEC.svg
  features:
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - navigation.indexes
    - navigation.sections
  palette:
    - scheme: default
      primary: custom
      accent: custom

# --- Estilos y scripts extra ---
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - assets/css/data_catalog.css
  - stylesheets/emergency_palette.css
extra_javascript:
  - assets/js/data_catalog.js

# --- Navegación ---
nav:
  - welcome/index.md
  - Getting Started:
      - getting_started/index.md
      - getting_started/what_is_pgtec.md
      - getting_started/data_and_services.md
      - getting_started/join_data_space.md
  - Data Sources:
      - data_sources/index.md 
      # - data_sources/metadata_datasources/siah_datasource.md
      # - data_sources/metadata_datasources/siar_datasource.md
      # - data_sources/metadata_datasources/aemet_datasource.md
      # - data_sources/metadata_datasources/aemet_rocio_datasource.md
      # - data_sources/metadata_datasources/aemet_spain_datasource.md
      # - data_sources/metadata_datasources/copernicus_datasource.md
      # - data_sources/metadata_datasources/mswep_datasource.md
      # - data_sources/metadata_datasources/cedex_datasource.md
      # - data_sources/metadata_datasources/avsre_datasource.md
  - Data Flow:
      - pipeline/index.md
      - pipeline/requirements.md
      - pipeline/setup.md
      - pipeline/example_copernicus.md

  - Smart Data Models:
      - SmartDataModels/index.md
      - SmartDataModels/WeatherForecastSeries.md
      - SmartDataModels/WeatherObserved.md
      - SmartDataModels/StreamFlow.md

  - SmartFlow:
      - SmartFlow/index.md
      # - SmartFlow/metadata_scripts/Harmonie_AEMET.md
      # - SmartFlow/metadata_scripts/GEPS_ENS_CNC.md
      # - SmartFlow/metadata_scripts/DWD_ICON.md
      # - SmartFlow/metadata_scripts/ARPEGE.md
      # - SmartFlow/metadata_scripts/AIFS_ECMWF.md
      # - SmartFlow/metadata_scripts/GFS_NOAA.md
      # - SmartFlow/metadata_scripts/IFS9km_ECMWF.md
      # - SmartFlow/metadata_scripts/Seas5_ECWMF_copernicus.md
      # - SmartFlow/metadata_scripts/EFAS.md
      # - SmartFlow/metadata_scripts/EFFIS.md

  - Data Space:
      - DataSpace/index.md
      - DataSpace/arquitecture.md
      - Identities and Credentials:
          - Overview: DataSpace/identities_and_credentials.md  
          - DID: DataSpace/did.md
      

# --- Extensiones de Markdown ---
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: false
      toc_depth: 3
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
